language: cpp
compiler:
    - gcc
    - clang
branches:
   only:
    - master
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libeigen3-dev libarpack2-dev cmake valgrind python-numpy xsltproc libgtest-dev
    - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=1
script: make
after_success: ctest -VV
after_script:
    - python test/generate_swissroll.py 100
    - CALLENV='valgrind --leak-check=full --xml=yes --xml-file=/dev/stdout' 
      TAPKEE_ELF='bin/tapkee' 
      INPUT_FILE='input.dat' 
      OUTPUT_FILE='/dev/null' 
      TRANSFORM='xsltproc test/valgrind_tests_transformer.xslt /dev/stdin' 
      test/valgrind_run_all.sh 
notifications:
    email:
        on_failure: always
